"""Definitions for go-eCharger sensors exposed via MQTT."""
from __future__ import annotations

from dataclasses import dataclass
import json
import logging

from homeassistant.components.sensor import (
    STATE_CLASS_MEASUREMENT,
    STATE_CLASS_TOTAL_INCREASING,
    SensorDeviceClass,
    SensorEntityDescription,
)
from homeassistant.const import (
    CURRENCY_CENT,
    ELECTRIC_CURRENT_AMPERE,
    ELECTRIC_POTENTIAL_VOLT,
    ENERGY_WATT_HOUR,
    FREQUENCY_HERTZ,
    PERCENTAGE,
    POWER_KILO_WATT,
    POWER_WATT,
    SIGNAL_STRENGTH_DECIBELS,
    TEMP_CELSIUS,
    TIME_MILLISECONDS,
    TIME_SECONDS,
)
from homeassistant.helpers.entity import EntityCategory

from . import GoEChargerEntityDescription, GoEChargerStatusCodes

_LOGGER = logging.getLogger(__name__)


@dataclass
class GoEChargerSensorEntityDescription(
    GoEChargerEntityDescription, SensorEntityDescription
):
    """Sensor entity description for go-eCharger."""

    domain: str = "sensor"


def remap_configured_phases(value, unused) -> int | None:
    """Remap configured phases."""
    if int(value) == 1:
        return 1
    if int(value) == 2:
        return 3
    return None


def extract_charging_duration(value, attribute) -> int | None:
    """Extract charging duration from object.

    Example value: {"type":1,"value":0}
    """
    data = json.loads(value)
    if "type" in data and data["type"] == int(attribute):
        return data["value"]

    return None


def extract_energy_from_cards(value, key) -> int | None:
    """Extract energy from selected card of the cards object.

    Example value: [{"name":"User 1","energy":0,"cardId":true},{...}, ...]
    """
    try:
        data = json.loads(value)[int(key)]
        return data.get("energy")
    except IndexError:
        return None


def remove_quotes(value, unused):
    """Remove quotes helper."""
    return value.replace('"', "")


def json_array_to_csv(value, unused) -> str:
    """Transform JSON array to CSV."""
    if value == "null":
        return ""

    return ", ".join(json.loads(value))


def extract_item_from_array_to_float(value, key) -> float:
    """Extract item from array to float."""
    return float(json.loads(value)[int(key)])


def extract_item_from_array_to_int(value, key) -> int:
    """Extract item from array to int."""
    return int(json.loads(value)[int(key)])


def extract_item_from_array_to_bool(value, key) -> bool:
    """Extract item from array to int."""
    return bool(json.loads(value)[int(key)])


def transform_code(value, mapping_table) -> str:
    """Transform codes into a human readable string."""
    try:
        return getattr(GoEChargerStatusCodes, mapping_table)[int(value)]
    except KeyError:
        return "Definition missing for code %s" % value


SENSORS: tuple[GoEChargerSensorEntityDescription, ...] = (
    GoEChargerSensorEntityDescription(
        key="+/result",
        name="Last set config key result",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ama",
        name="Maximum current limit",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ate",
        name="Automatic stop energy",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="att",
        name="Automatic stop time",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_SECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="awc",
        name="Awattar country",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="awp",
        name="Awattar maximum price threshold",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=CURRENCY_CENT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cch",
        name="Color charging",
        state=remove_quotes,
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:format-color-fill",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cco",
        name="Car consumption",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="App only",
    ),
    GoEChargerSensorEntityDescription(
        key="cfi",
        name="Color finished",
        state=remove_quotes,
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:format-color-fill",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cid",
        name="Color idle",
        state=remove_quotes,
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:format-color-fill",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="clp",
        name="Current limit presets",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ct",
        name="Car type",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="App only",
    ),
    GoEChargerSensorEntityDescription(
        key="cwc",
        name="Color wait for car",
        state=remove_quotes,
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:format-color-fill",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="dwo",
        name="Charging energy limit",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="fna",
        name="Friendly name",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="frc",
        name="Force state",
        state=transform_code,
        attribute="frc",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:auto-fix",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="frc",
        name="Force state code",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:auto-fix",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lbr",  # 0...255
        name="LED brightness",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:brightness-6",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lmo",
        name="Logic mode",
        state=transform_code,
        attribute="lmo",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lof",
        name="Load balancing fallback current",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="log",
        name="Load balancing group id",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lop",
        name="Load balancing priority",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lot",
        name="Load balancing total ampere",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="loty",
        name="Load balancing type",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="map",
        name="Load mapping",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mca",
        name="Minimum charging current",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="mci",
        name="Minimum charging interval",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mcpd",
        name="Minimum charge pause duration",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mptwt",
        name="Minimum phase toggle wait time",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mpwst",
        name="Minimum phase wish switch time",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="pass",
        name="User password",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="psmd",
        name="Force single phase duration",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="sch_satur",
        name="Scheduler saturday",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="sch_sund",
        name="Scheduler sunday",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="sch_week",
        name="Scheduler weekday",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="spl3",
        name="Three phase switch level",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,  # This unit is a best guess
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="sumd",
        name="Simulate unplugging duration",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tds",
        name="Timezone daylight saving mode",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tof",
        name="Timezone offset in minutes",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ts",
        name="Time server",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tssi",
        name="Time server sync interval",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tssm",
        name="Time server sync mode",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tsss",
        name="Time server sync status",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ust",
        name="Cable unlock mode",
        state=transform_code,
        attribute="ust",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:account-lock-open",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ust",
        name="Cable unlock mode code",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:account-lock-open",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="wak",
        name="WiFi accesspoint encryption key",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="wan",
        name="WiFi accesspoint network name",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="wifis",
        name="WiFi configurations",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="apd",
        name="Firmware description",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="arv",
        name="App recommended version",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ecf",
        name="ESP CPU frequency",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="eci",
        name="ESP Chip info",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="eem",
        name="ESP CPU frequency",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="efi",
        name="ESP Flash info",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="facwak",
        name="WiFi accesspoint key reset value",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="fem",
        name="Flash encryption mode",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ffna",
        name="Factory friendly name",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="fwan",
        name="Factory WiFi accesspoint network name",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="fwc",
        name="Firmware from car control",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="fwv",
        name="Firmware version",
        state=remove_quotes,
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="mod",
        name="Hardware version",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="oem",
        name="Manufacturer",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="otap",
        name="Active OTA partition",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="part",
        name="Partition table",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="pto",
        name="Partition table offset in flash",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="sse",
        name="Serial number",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="typ",
        name="Device type",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="var",
        name="Device variant",
        entity_category=None,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_KILO_WATT,
        state_class=None,
        icon="mdi:image-size-select-large",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="del",
        name="Delete card",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="delw",
        name="Delete STA config",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lrn",
        name="Learn card",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="oct",
        name="Firmware update trigger",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="acu",
        name="Maximum allowed current",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="amt",
        name="Current temperature limit",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=TEMP_CELSIUS,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="atp",
        name="Next trip plan data",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="awcp",
        name="Awattar current price",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="awpl",
        name="Awattar price list",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="car",
        name="Car state",
        state=transform_code,
        attribute="car",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:heart-pulse",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cbl",
        name="Cable maximum current",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ccu",
        name="Charge controller update progress",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ccw",
        name="Connected WiFi",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="JSON decoding required. Values non-essential",
    ),
    GoEChargerSensorEntityDescription(
        key="cdi",
        name="Charging duration",
        state=extract_charging_duration,
        attribute="1",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cdi",
        name="Charging duration counter",
        state=extract_charging_duration,
        attribute="0",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:counter",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cus",
        name="Cable unlock status code",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:shield-lock-open-outline",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cus",
        name="Cable unlock status",
        state=transform_code,
        attribute="cus",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:shield-lock-open-outline",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cwsca",
        name="Cloud websocket connected",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="efh",
        name="ESP free heap",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="efh32",
        name="ESP free heap 32bit aligned",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="efh8",
        name="ESP free heap 8bit aligned",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ehs",
        name="ESP heap size",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="emfh",
        name="ESP minimum free heap since boot",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="emhb",
        name="ESP maximum size of allocated heap block since boot",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="err",
        name="Error",
        state=transform_code,
        attribute="err",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:alert-circle-outline",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="err",
        name="Error code",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:alert-circle-outline",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="esr",
        name="RTC reset reason",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="eto",
        name="Total energy",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="etop",
        name="Total energy persisted",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ffb",
        name="Lock feedback",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ffba",
        name="Lock feedback age",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="fhz",
        name="Grid frequency",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=FREQUENCY_HERTZ,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:current-ac",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="fsptws",
        name="Force single phase toggle wished since",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="host",
        name="Hostname on STA interface",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lbp",
        name="Last button press",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lccfc",
        name="Last car state changed from charging",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lccfi",
        name="Last car state changed from idle",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lcctc",
        name="Last car state changed to charging",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lck",
        name="Effective lock setting",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="led",
        name="LED animation details",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lfspt",
        name="Last force single phase toggle",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lmsc",
        name="Last mode change",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="loa",
        name="Load balancing available current",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="loc",
        name="Local time",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Valueless with a high update interval of 1s",
    ),
    GoEChargerSensorEntityDescription(
        key="lom",
        name="Load balancing members",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        icon="mdi:account-multiple",
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="los",
        name="Load balancing status",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lssfc",
        name="WiFi station disconnected since",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lsstc",
        name="WiFi station connected since",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mcpea",
        name="Minimum charge pause ends at",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mmp",
        name="Maximum measured charging power",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="modelStatus",
        name="Status",
        state=transform_code,
        attribute="modelStatus",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:heart-pulse",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="modelStatus",
        name="Status code",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:heart-pulse",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="msi",
        name="Reason why we allow charging or not",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="0",
        name="Voltage L1",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="1",
        name="Voltage L2",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="2",
        name="Voltage L3",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="3",
        name="Voltage N",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="4",
        name="Current L1",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="5",
        name="Current L2",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="6",
        name="Current L3",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="7",
        name="Power L1",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="8",
        name="Power L2",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="9",
        name="Power L3",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="10",
        name="Power N",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="11",
        name="Current power",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="12",
        name="Power factor L1",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="13",
        name="Power factor L2",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="14",
        name="Power factor L3",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="15",
        name="Power factor N",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="oca",
        name="OTA cloud app description",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ocl",
        name="OTA from cloud length",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ocm",
        name="OTA from cloud message",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ocp",
        name="OTA from cloud progress",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ocs",
        name="OTA from cloud status",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ocu",
        name="List of available firmware versions",
        state=json_array_to_csv,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="onv",
        name="Newest OTA version",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="pwm",
        name="Phase wish mode for debugging",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="qsc",
        name="Queue size cloud",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="qsw",
        name="Queue size web",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="rbc",
        name="Reboot counter",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        icon="mdi:counter",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="rbt",
        name="Uptime",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="TODO: Convert to a timestamp first",
    ),
    GoEChargerSensorEntityDescription(
        key="rcd",
        name="Residual current detection",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="rfb",
        name="Relay feedback",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="rr",
        name="ESP reset reason",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="rssi",
        name="WiFi signal strength",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.SIGNAL_STRENGTH,
        native_unit_of_measurement=SIGNAL_STRENGTH_DECIBELS,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="scaa",
        name="WiFi scan age",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="scan",
        name="WiFi scan result",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="scas",
        name="WiFi scan status",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tma",
        name="Temperature sensor 1",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=TEMP_CELSIUS,
        state_class=STATE_CLASS_MEASUREMENT,
        attribute="0",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="tma",
        name="Temperature sensor 2",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=TEMP_CELSIUS,
        state_class=STATE_CLASS_MEASUREMENT,
        attribute="1",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="tpa",
        name="Total power average",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="trx",
        name="Transaction",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:message-text-lock-outline",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="tsom",
        name="Time server operating mode",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="utc",
        name="UTC time",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Valueless with a high update interval of 1s",
    ),
    GoEChargerSensorEntityDescription(
        key="wcch",
        name="Clients via http",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="wccw",
        name="Clients via websocket",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="wh",
        name="Charged energy",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="wsms",
        name="WiFi state machine state",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="wst",  # 3: connect, 0: not connected
        name="WiFi station status",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="psm",
        name="Configured phases",
        state=remap_configured_phases,
        entity_category=EntityCategory.CONFIG,
        icon="mdi:current-ac",
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cards",
        name="Charged energy card 1",
        state=extract_energy_from_cards,
        attribute="0",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cards",
        name="Charged energy card 2",
        state=extract_energy_from_cards,
        attribute="1",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cards",
        name="Charged energy card 3",
        state=extract_energy_from_cards,
        attribute="2",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cards",
        name="Charged energy card 4",
        state=extract_energy_from_cards,
        attribute="3",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cards",
        name="Charged energy card 5",
        state=extract_energy_from_cards,
        attribute="4",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cards",
        name="Charged energy card 6",
        state=extract_energy_from_cards,
        attribute="5",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cards",
        name="Charged energy card 7",
        state=extract_energy_from_cards,
        attribute="6",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cards",
        name="Charged energy card 8",
        state=extract_energy_from_cards,
        attribute="7",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cards",
        name="Charged energy card 9",
        state=extract_energy_from_cards,
        attribute="8",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cards",
        name="Charged energy card 10",
        state=extract_energy_from_cards,
        attribute="9",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ppv",
        name="Power from Solar Panels (from ids)",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="pgrid",
        name="Power from grid (from ids)",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="pakku",
        name="Power from battery (from ids)",
        entity_category=EntityCategory.CONFIG,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
)
