"""Definitions for go-eCharger sensors exposed via MQTT."""
from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
import json
import logging

from homeassistant.components.binary_sensor import BinarySensorEntityDescription
from homeassistant.components.number import NumberEntityDescription
from homeassistant.components.select import SelectEntityDescription
from homeassistant.components.sensor import (
    STATE_CLASS_MEASUREMENT,
    STATE_CLASS_TOTAL_INCREASING,
    SensorEntityDescription,
)
from homeassistant.components.switch import SwitchEntityDescription
from homeassistant.const import (
    CURRENCY_CENT,
    DEVICE_CLASS_CURRENT,
    DEVICE_CLASS_ENERGY,
    DEVICE_CLASS_POWER,
    DEVICE_CLASS_POWER_FACTOR,
    DEVICE_CLASS_SIGNAL_STRENGTH,
    DEVICE_CLASS_TEMPERATURE,
    DEVICE_CLASS_VOLTAGE,
    ELECTRIC_CURRENT_AMPERE,
    ELECTRIC_POTENTIAL_VOLT,
    ENERGY_WATT_HOUR,
    FREQUENCY_HERTZ,
    PERCENTAGE,
    POWER_KILO_WATT,
    POWER_WATT,
    SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
    TEMP_CELSIUS,
    TIME_MILLISECONDS,
    TIME_SECONDS,
)
from homeassistant.helpers.entity import EntityCategory, EntityDescription

_LOGGER = logging.getLogger(__name__)


class GoEChargerStatusCodes:
    """Status code container."""

    car = {
        0: "",
        1: "Idle",
        2: "Charging",
        3: "Wait for car",
        4: "Complete",
        5: "Error",
    }

    err = {
        0: "",
        1: "Residual current circuit breaker",
        3: "Phase fault",
        8: "No ground",
        10: "Internal error",
    }

    modelStatus = {
        0: "Not charging because no charge control data",
        1: "Not charging because of over temperature",
        2: "Not charging because access control wait",
        3: "Charging because of forced ON",
        4: "Not charging because of forced OFF",
        5: "Not charging because of scheduler",
        6: "Not charging because of energy limit",
        7: "Charging because Awattar price under threshold",
        8: "Charging because of automatic stop test charging",
        9: "Charging because of automatic stop not enough time",
        10: "Charging because of automatic stop",
        11: "Charging because of automatic stop no clock",
        12: "Charging because of PV surplus",
        13: "Charging because of fallback (GoE Default)",
        14: "Charging because of fallback (GoE Scheduler)",
        15: "Charging because of fallback (Default)",
        16: "Not charging because of fallback (GoE Awattar)",
        17: "Not charging because of fallback (Awattar)",
        18: "Not charging because of fallback (Automatic Stop)",
        19: "Charging because of car compatibility (Keep Alive)",
        20: "Charging because charge pause not allowed",
        21: "Unknown",
        22: "Not charging because simulate unplugging",
        23: "Not charging because of phase switch",
        24: "Not charging because of minimum pause duration",
    }

    ust = {
        0: "Normal",
        1: "Auto Unlock",
        2: "Always Lock",
    }

    frc = {
        0: "Neutral",
        1: "Off",
        2: "On",
    }

    lmo = {
        3: "Default",
        4: "Awattar",
        5: "Automatic Stop",
    }

    psm = {
        1: "1 Phase",
        2: "3 Phases",
    }


@dataclass
class GoEChargerEntityDescription(EntityDescription):
    """Generic entity description for go-eCharger."""

    state: Callable | None = None
    attribute: str = "0"
    domain: str = "generic"
    disabled: bool | None = None
    disabled_reason: str | None = None


@dataclass
class GoEChargerBinarySensorEntityDescription(
    GoEChargerEntityDescription, BinarySensorEntityDescription
):
    """Binary sensor entity description for go-eCharger."""

    domain: str = "binary_sensor"


@dataclass
class GoEChargerSelectEntityDescription(
    GoEChargerEntityDescription, SelectEntityDescription
):
    """Select entity description for go-eCharger."""

    options: list[str] | None = None
    domain: str = "select"


@dataclass
class GoEChargerSensorEntityDescription(
    GoEChargerEntityDescription, SensorEntityDescription
):
    """Sensor entity description for go-eCharger."""

    domain: str = "sensor"


@dataclass
class GoEChargerSwitchEntityDescription(
    GoEChargerEntityDescription, SwitchEntityDescription
):
    """Switch entity description for go-eCharger."""

    domain: str = "switch"
    payload_on: str = "true"
    payload_off: str = "false"


@dataclass
class GoEChargerNumberEntityDescription(
    GoEChargerEntityDescription, NumberEntityDescription
):
    """Number entity description for go-eCharger."""

    domain: str = "number"


def remap_configured_phases(value, unused) -> int | None:
    """Remap configured phases."""
    if int(value) == 1:
        return 1
    if int(value) == 2:
        return 3
    return None


def remove_quotes(value, unused):
    """Remove quotes helper."""
    return value.replace('"', "")


def json_array_to_csv(value, unused) -> str:
    """Transform JSON array to CSV."""
    return ", ".join(json.loads(value))


def extract_item_from_array_to_float(value, key) -> float:
    """Extract item from array to float."""
    return float(json.loads(value)[int(key)])


def extract_item_from_array_to_int(value, key) -> int:
    """Extract item from array to int."""
    return int(json.loads(value)[int(key)])


def transform_code(value, mapping_table) -> str:
    """Transform codes into a human readable string."""
    try:
        return getattr(GoEChargerStatusCodes, mapping_table)[int(value)]
    except KeyError:
        return "Definition missing for code %s" % value


"""
https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-en.md

Known but undocumented keys/topics:

- cards: [{"name":"User 1","energy":0,"cardId":true},{"name":"User 2","energy":0,"cardId":false},...,{"name":"User 10","energy":0,"cardId":false}]
- deltap: 0
- dll: https://data.v3.go-e.io/export?e=redacted
- dns: {"dns":"0.0.0.0"}
- hla: false
- lrc: null
- lri: null
- lrr: null
- men: false
- pakku: null
- pgrid: null
- ppv: null

"""

BINARY_SENSORS: tuple[GoEChargerBinarySensorEntityDescription, ...] = (
    GoEChargerBinarySensorEntityDescription(
        key="cca",
        name="Cloud websocket use client auth",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerBinarySensorEntityDescription(
        key="ocuca",
        name="OTA cloud use client auth",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerBinarySensorEntityDescription(
        key="sbe",
        name="Secure boot enabled",
        entity_category=None,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerBinarySensorEntityDescription(
        key="adi",
        name="Is the 16a adapter used",  # 0: NO_ADAPTER, 1: 16A_ADAPTER
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerBinarySensorEntityDescription(
        key="cpe",
        name="Charge control requests the cp signal enabled or not immediately",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerBinarySensorEntityDescription(
        key="cpr",
        name="CP enable request",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerBinarySensorEntityDescription(
        key="cws",
        name="Cloud websocket started",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerBinarySensorEntityDescription(
        key="cwsc",
        name="Cloud websocket connected",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerBinarySensorEntityDescription(
        key="fsp",
        name="Force single phase",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
        disabled_reason="Is always false. Please use `psm` instead",
    ),
    GoEChargerBinarySensorEntityDescription(
        key="lwcf",
        name="Last failed WiFi connect",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerBinarySensorEntityDescription(
        key="tlf",
        name="Test charging finished",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerBinarySensorEntityDescription(
        key="tls",
        name="Test charging started",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
)

SENSORS: tuple[GoEChargerSensorEntityDescription, ...] = (
    GoEChargerSensorEntityDescription(
        key="acs",
        name="Access control user setting",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ama",
        name="Maximum current limit",
        entity_category=EntityCategory.CONFIG,
        device_class=DEVICE_CLASS_CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ate",
        name="Automatic stop energy",
        entity_category=EntityCategory.CONFIG,
        device_class=DEVICE_CLASS_ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="att",
        name="Automatic stop time",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_SECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="awc",
        name="Awattar country",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="awp",
        name="Awattar maximum price threshold",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=CURRENCY_CENT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cch",
        name="Color charging",
        state=remove_quotes,
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:format-color-fill",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cco",
        name="Car consumption",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="App only",
    ),
    GoEChargerSensorEntityDescription(
        key="cfi",
        name="Color finished",
        state=remove_quotes,
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:format-color-fill",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cid",
        name="Color idle",
        state=remove_quotes,
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:format-color-fill",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="clp",
        name="Current limit presets",
        entity_category=EntityCategory.CONFIG,
        device_class=DEVICE_CLASS_CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ct",
        name="Car type",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="App only",
    ),
    GoEChargerSensorEntityDescription(
        key="cwc",
        name="Color wait for car",
        state=remove_quotes,
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:format-color-fill",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="dwo",
        name="Charging energy limit",
        entity_category=EntityCategory.CONFIG,
        device_class=DEVICE_CLASS_ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="fna",
        name="Friendly name",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="frc",
        name="Force state",
        state=transform_code,
        attribute="frc",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="frc",
        name="Force state code",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lbr",  # 0...255
        name="LED brightness",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:brightness-6",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lmo",
        name="Logic mode",
        state=transform_code,
        attribute="lmo",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lof",
        name="Load fallback",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="log",
        name="Load group id",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lop",
        name="Load priority",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lot",
        name="Load balancing total ampere",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="loty",
        name="Load balancing type",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="map",
        name="Load mapping",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mca",
        name="Minimum charging current",
        entity_category=EntityCategory.CONFIG,
        device_class=DEVICE_CLASS_CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="mci",
        name="Minimum charging interval",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mcpd",
        name="Minimum charge pause duration",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mptwt",
        name="Minimum phase toggle wait time",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mpwst",
        name="Minimum phase wish switch time",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="pass",
        name="User password",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="psmd",
        name="Force single phase duration",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="sch_satur",
        name="Scheduler saturday",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="sch_sund",
        name="Scheduler sunday",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="sch_week",
        name="Scheduler weekday",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="spl3",
        name="Three phase switch level",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="sumd",
        name="Simulate unplugging duration",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tds",
        name="Timezone daylight saving mode",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tof",
        name="Timezone offset in minutes",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ts",
        name="Time server",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tssi",
        name="Time server sync interval",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tssm",
        name="Time server sync mode",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tsss",
        name="Time server sync status",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ust",
        name="Unlock setting",
        state=transform_code,
        attribute="ust",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ust",
        name="Unlock setting code",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="wak",
        name="WiFi accesspoint encryption key",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="wan",
        name="WiFi accesspoint network name",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="wifis",
        name="WiFi configurations",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="apd",
        name="Firmware description",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="arv",
        name="App recommended version",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ecf",
        name="ESP CPU frequency",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="eci",
        name="ESP Chip info",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="eem",
        name="ESP CPU frequency",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="efi",
        name="ESP Flash info",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="facwak",
        name="WiFi accesspoint key reset value",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="fem",
        name="Flash encryption mode",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ffna",
        name="Factory friendly name",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="fwan",
        name="Factory WiFi accesspoint network name",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="fwc",
        name="Firmware from car control",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="fwv",
        name="Firmware version",
        state=remove_quotes,
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="mod",
        name="Hardware version",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="oem",
        name="Manufacturer",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="otap",
        name="Active OTA partition",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="part",
        name="Partition table",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="pto",
        name="Partition table offset in flash",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="sse",
        name="Serial number",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="typ",
        name="Device type",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="var",
        name="Device variant",
        entity_category=None,
        device_class=None,
        native_unit_of_measurement=POWER_KILO_WATT,
        state_class=None,
        icon="mdi:image-size-select-large",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="del",
        name="Delete card",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="delw",
        name="Delete STA config",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lrn",
        name="Learn card",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="oct",
        name="Firmware update trigger",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="acu",
        name="Maximum allowed current",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="amt",
        name="Current temperature limit",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_TEMPERATURE,
        native_unit_of_measurement=TEMP_CELSIUS,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="atp",
        name="Next trip plan data",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="awcp",
        name="Awattar current price",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="awpl",
        name="Awattar price list",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="car",
        name="Car state",
        state=transform_code,
        attribute="car",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:heart-pulse",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cbl",
        name="Cable maximum current limit",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="ccu",
        name="Charge controller update progress",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ccw",
        name="Connected WiFi",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="JSON decoding required. Values non-essential",
    ),
    GoEChargerSensorEntityDescription(
        key="cdi",
        name="Charging duration info",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="cus",
        name="Cable unlock status",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="cwsca",
        name="Cloud websocket connected",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="efh",
        name="ESP free heap",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="efh32",
        name="ESP free heap 32bit aligned",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="efh8",
        name="ESP free heap 8bit aligned",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ehs",
        name="ESP heap size",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="emfh",
        name="ESP minimum free heap since boot",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="emhb",
        name="ESP maximum size of allocated heap block since boot",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="err",
        name="Error",
        state=transform_code,
        attribute="err",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:alert-circle-outline",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="err",
        name="Error code",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:alert-circle-outline",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="esr",
        name="RTC reset reason",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="eto",
        name="Total energy",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="etop",
        name="Total energy persisted",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ffb",
        name="Lock feedback",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ffba",
        name="Lock feedback age",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="fhz",
        name="Grid frequency",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=FREQUENCY_HERTZ,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:current-ac",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="fsptws",
        name="Force single phase toggle wished since",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="host",
        name="Hostname on STA interface",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lbp",
        name="Last button press",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lccfc",
        name="Last car state changed from charging",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lccfi",
        name="Last car state changed from idle",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lcctc",
        name="Last car state changed to charging",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="lck",
        name="Effective lock setting",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="led",
        name="LED animation details",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lfspt",
        name="Last force single phase toggle",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lmsc",
        name="Last model status change",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="loa",
        name="Load balancing ampere",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="loc",
        name="Local time",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Valueless with a high update interval of 1s",
    ),
    GoEChargerSensorEntityDescription(
        key="lom",
        name="Load balancing members",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="los",
        name="Load balancing status",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lssfc",
        name="WiFi station disconnected since",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="lsstc",
        name="WiFi station connected since",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mcpea",
        name="Minimum charge pause ends at",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=TIME_MILLISECONDS,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:timer-outline",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="mmp",
        name="Maximum measured charging power",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_POWER,
        native_unit_of_measurement=POWER_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="modelStatus",
        name="Status",
        state=transform_code,
        attribute="modelStatus",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:heart-pulse",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="modelStatus",
        name="Status code",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:heart-pulse",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="msi",
        name="Reason why we allow charging or not",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="0",
        name="Voltage L1",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_VOLTAGE,
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="1",
        name="Voltage L2",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_VOLTAGE,
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="2",
        name="Voltage L3",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_VOLTAGE,
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="3",
        name="Voltage N",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_VOLTAGE,
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="4",
        name="Current L1",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="5",
        name="Current L2",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="6",
        name="Current L3",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_CURRENT,
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="7",
        name="Power L1",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_POWER,
        native_unit_of_measurement=POWER_KILO_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="8",
        name="Power L2",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_POWER,
        native_unit_of_measurement=POWER_KILO_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="9",
        name="Power L3",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_POWER,
        native_unit_of_measurement=POWER_KILO_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="10",
        name="Power N",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_POWER,
        native_unit_of_measurement=POWER_KILO_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="11",
        name="Power total",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_POWER,
        native_unit_of_measurement=POWER_KILO_WATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="12",
        name="Power factor L1",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="13",
        name="Power factor L2",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="14",
        name="Power factor L3",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="nrg",
        attribute="15",
        name="Power factor N",
        state=extract_item_from_array_to_int,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="oca",
        name="OTA cloud app description",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ocl",
        name="OTA from cloud length",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ocm",
        name="OTA from cloud message",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ocp",
        name="OTA from cloud progress",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ocs",
        name="OTA from cloud status",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="ocu",
        name="List of available firmware versions",
        state=json_array_to_csv,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="onv",
        name="Newest OTA version",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="pha",
        name="Phases",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="pwm",
        name="Phase wish mode for debugging",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="qsc",
        name="Queue size cloud",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="qsw",
        name="Queue size web",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="rbc",
        name="Reboot counter",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_TOTAL_INCREASING,
        icon="mdi:counter",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="rbt",
        name="Uptime",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="TODO: Convert to a timestamp first",
    ),
    GoEChargerSensorEntityDescription(
        key="rcd",
        name="Residual current detection",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="rfb",
        name="Relay feedback",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="rr",
        name="ESP reset reason",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="rssi",
        name="WiFi signal strength",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_SIGNAL_STRENGTH,
        native_unit_of_measurement=SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="scaa",
        name="WiFi scan age",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="scan",
        name="WiFi scan result",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="scas",
        name="WiFi scan status",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="tma",
        name="Temperature sensor 1",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_TEMPERATURE,
        native_unit_of_measurement=TEMP_CELSIUS,
        state_class=STATE_CLASS_MEASUREMENT,
        attribute="0",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="tma",
        name="Temperature sensor 2",
        state=extract_item_from_array_to_float,
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_TEMPERATURE,
        native_unit_of_measurement=TEMP_CELSIUS,
        state_class=STATE_CLASS_MEASUREMENT,
        attribute="1",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="tpa",
        name="Total power average",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="trx",
        name="Transaction",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="tsom",
        name="Time server operating mode",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="utc",
        name="UTC time",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Valueless with a high update interval of 1s",
    ),
    GoEChargerSensorEntityDescription(
        key="wcch",
        name="Clients via http",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="wccw",
        name="Clients via websocket",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="wh",
        name="Energy since car connected",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=DEVICE_CLASS_ENERGY,
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSensorEntityDescription(
        key="wsms",
        name="WiFi state machine state",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="wst",  # 3: connect, 0: not connected
        name="WiFi station status",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=STATE_CLASS_MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSensorEntityDescription(
        key="psm",
        name="Configured phases",
        state=remap_configured_phases,
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
)

SWITCHES: tuple[GoEChargerSwitchEntityDescription, ...] = (
    GoEChargerSwitchEntityDescription(
        key="bac",
        name="Allow current change by button",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSwitchEntityDescription(
        key="ara",
        name="Automatic stop mode",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEChargerSwitchEntityDescription(
        key="wen",
        name="WiFi enabled",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="tse",
        name="Time server enabled",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="sdp",
        name="Button allow force change",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="nmo",
        name="Norway mode",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="lse",
        name="LED off on standby",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="awe",
        name="Awattar mode",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=True,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="acp",
        name="Allow charge pause",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=True,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="esk",
        name="Energy set",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="App only",
    ),
    GoEChargerSwitchEntityDescription(
        key="su",
        name="Simulate unplugging",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="hws",
        name="HTTP STA reachable",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="hsa",
        name="HTTP STA authentication",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="loe",
        name="Load balancing enabled",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="upo",
        name="Unlock power outage",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="cwe",
        name="Cloud websocket enabled",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="Not exposed via MQTT in firmware 053.1",
    ),
    GoEChargerSwitchEntityDescription(
        key="psm",
        name="Force single phase",
        payload_on="1",
        payload_off="2",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
)

NUMBERS: tuple[GoEChargerNumberEntityDescription, ...] = (
    GoEChargerNumberEntityDescription(
        key="amp",
        name="Requested current",
        entity_category=EntityCategory.CONFIG,
        device_class=DEVICE_CLASS_CURRENT,
        entity_registry_enabled_default=True,
        disabled=False,
        max_value=32,
        min_value=6,
        step=1,
    ),
)

SELECTS: tuple[GoEChargerSelectEntityDescription, ...] = (
    GoEChargerSelectEntityDescription(
        key="lmo",
        name="Logic mode",
        entity_category=EntityCategory.CONFIG,
        device_class=None,
        entity_registry_enabled_default=True,
        disabled=False,
        options=["3", "4", "5"],
    ),
)
