name: HACS
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hacs/action@main
        with:
          category: integration
